DROP TABLE f_bdt_catalogue;
DROP TYPE livre;

CREATE OR REPLACE TYPE livre AS OBJECT (
ISBN CHAR(13),
TITRE VARCHAR2(255),
AUTEUR VARCHAR2(255),
LANGUE CHAR(3),
PUBLICATION VARCHAR2(50),
EDITEUR VARCHAR2(255),
GENRE VARCHAR2(255),
MEMBER FUNCTION getisbn RETURN char(13),
MEMBER FUNCTION gettitre RETURN varchar2(255),
MEMBER FUNCTION getauteur RETURN varchar2(255),
MEMBER FUNCTION getlangue RETURN char(3),
MEMBER FUNCTION getpublication RETURN varchar2(50),
MEMBER FUNCTION getediteur RETURN varchar2(255),
MEMBER FUNCTION getgenre RETURN varchar2(255)
);