CREATE OR REPLACE TYPE vente AS OBJECT (
ticket NUMBER(13),
fk_date CHAR(10),
fk_magasin VARCHAR2(10),
fk_isbn CHAR(13),

MEMBER FUNCTION getTicket RETURN NUMBER,
MEMBER FUNCTION getMagasin RETURN VARCHAR2,
MEMBER FUNCTION getDate RETURN DATE,
MEMBER FUNCTION getIsbn RETURN VARCHAR2
);