DROP TABLE l_bde_vente;

CREATE TABLE l_bde_vente (
  date_vente VARCHAR2(10),
  mag VARCHAR2(4),
  licence VARCHAR2(11)
)
ORGANIZATION EXTERNAL
(TYPE ORACLE_LOADER
DEFAULT DIRECTORY nf26p024lightsaberdatafile
ACCESS PARAMETERS
(
RECORDS DELIMITED BY newline
SKIP 1
characterset UTF8
BADFILE nf26p024lightsabertmp:'LightsaberInc3755.csv.bad'
LOGFILE nf26p024lightsabertmp:'LightsaberInc3755.csv.log'
FIELDS TERMINATED BY ';'
OPTIONALLY ENCLOSED BY '"'
)
LOCATION ('LightsaberInc3755'))
REJECT LIMIT UNLIMITED;