DROP TABLE l_bdt_date;

CREATE OR REPLACE TYPE typeDate AS OBJECT (
ddate VARCHAR(10),

MEMBER FUNCTION getDat RETURN date,
MEMBER FUNCTION getJds RETURN varchar2,
MEMBER FUNCTION getSem RETURN number,
MEMBER FUNCTION getMon RETURN number,
MEMBER FUNCTION getTri RETURN number

);